### ISSUE TITLE
Make WPEs for Data Clients

### ISSUE THREAD

**Issue by ram-nad** [wildfirepy/WildfirePy-WPEs#8]
We have already started working on adding the Data Clients to the repository. We need a WPE explaining the need for data clients, description about the ones we are adding, other viable options, etc.

**Comment by Raahul-Singh** [comment]
I don't think that that constitutes a WPE. WPEs are enhancements, like the formation of a senate or An early warning system.
Clients are essential modules. Not enhancements.
